// This file was auto-generated by Fern from our API Definition.

import { ImdbClient } from "./api/resources/imdb/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";

export declare namespace CernApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CernApiClient {
    protected readonly _options: NormalizedClientOptions<CernApiClient.Options>;
    protected _imdb: ImdbClient | undefined;

    constructor(options: CernApiClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get imdb(): ImdbClient {
        return (this._imdb ??= new ImdbClient(this._options));
    }
}
