// This file was auto-generated by Fern from our API Definition.

import type * as CernApi from "../../../index.js";

export interface Movie {
    id: CernApi.MovieId;
    title: string;
    /** The rating scale out of ten stars */
    rating: number;
}
